/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Pins v5.0
processor: LPC55S69
package_id: LPC55S69JBD100
mcu_data: ksdk2_0
processor_version: 5.0.0
pin_labels:
- {pin_num: '64', pin_signal: PIO1_18/SD1_POW_EN/SCT0_OUT5/PLU_OUT0, label: S2}
- {pin_num: '10', pin_signal: PIO1_9/ADC0_12/FC1_SCK/CT_INP4/SCT0_OUT2/FC4_CTS_SDA_SSEL0, label: S3}
- {pin_num: '88', pin_signal: PIO0_5/FC4_RXD_SDA_MOSI_DATA/CTIMER3_MAT0/SCT_GPI5/FC3_RTS_SCL_SSEL1/MCLK/SECURE_GPIO0_5, label: S1}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

#include "fsl_common.h"
#include "fsl_iocon.h"
#include "fsl_inputmux.h"
#include "pin_mux.h"

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitBootPins
 * Description   : Calls initialization functions.
 *
 * END ****************************************************************************************************************/
void BOARD_InitBootPins(void)
{
    BOARD_InitPins();
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitPins:
- options: {callFromInitBoot: 'true', coreID: cm33_core0, enableClock: 'true'}
- pin_list:
  - {pin_num: '92', peripheral: FLEXCOMM0, signal: RXD_SDA_MOSI_DATA, pin_signal: PIO0_29/FC0_RXD_SDA_MOSI_DATA/SD1_D2/CTIMER2_MAT3/SCT0_OUT8/CMP0_OUT/PLU_OUT2/SECURE_GPIO0_29,
    mode: inactive, slew_rate: standard, invert: disabled, digi_mode: digital, open_drain: disabled}
  - {pin_num: '94', peripheral: FLEXCOMM0, signal: TXD_SCL_MISO_WS, pin_signal: PIO0_30/FC0_TXD_SCL_MISO_WS/SD1_D3/CTIMER0_MAT0/SCT0_OUT9/SECURE_GPIO0_30, mode: inactive,
    slew_rate: standard, invert: disabled, digi_mode: digital, open_drain: disabled}
  - {pin_num: '88', peripheral: SECGPIO, signal: 'SECPIO0, 5', pin_signal: PIO0_5/FC4_RXD_SDA_MOSI_DATA/CTIMER3_MAT0/SCT_GPI5/FC3_RTS_SCL_SSEL1/MCLK/SECURE_GPIO0_5}
  - {pin_num: '88', peripheral: SECPINT, signal: 'SECPINT, 0', pin_signal: PIO0_5/FC4_RXD_SDA_MOSI_DATA/CTIMER3_MAT0/SCT_GPI5/FC3_RTS_SCL_SSEL1/MCLK/SECURE_GPIO0_5}
  - {pin_num: '64', peripheral: GPIO, signal: 'PIO1, 18', pin_signal: PIO1_18/SD1_POW_EN/SCT0_OUT5/PLU_OUT0, mode: pullUp, digi_mode: digital}
  - {pin_num: '64', peripheral: PINT, signal: 'PINT, 1', pin_signal: PIO1_18/SD1_POW_EN/SCT0_OUT5/PLU_OUT0}
  - {pin_num: '10', peripheral: GPIO, signal: 'PIO1, 9', pin_signal: PIO1_9/ADC0_12/FC1_SCK/CT_INP4/SCT0_OUT2/FC4_CTS_SDA_SSEL0, mode: pullUp, digi_mode: digital}
  - {pin_num: '10', peripheral: PINT, signal: 'PINT, 2', pin_signal: PIO1_9/ADC0_12/FC1_SCK/CT_INP4/SCT0_OUT2/FC4_CTS_SDA_SSEL0}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
/* Function assigned for the Cortex-M33 (Core #0) */
void BOARD_InitPins(void)
{
    /* Enables the clock for the Input Mux 0.: Enable Clock. */
    CLOCK_EnableClock(kCLOCK_InputMux);
    /* Enables the clock for the I/O controller.: Enable Clock. */
    CLOCK_EnableClock(kCLOCK_Iocon);
    /* PIO0_5 is selected for Secure PINT input 0 */
    INPUTMUX_AttachSignal(INPUTMUX, 0U, kINPUTMUX_GpioPort0Pin5ToPintSecsel);
    /* PIO1_18 is selected for PINT input 1 */
    INPUTMUX_AttachSignal(INPUTMUX, 1U, kINPUTMUX_GpioPort1Pin18ToPintsel);
    /* PIO1_9 is selected for PINT input 2 */
    INPUTMUX_AttachSignal(INPUTMUX, 2U, kINPUTMUX_GpioPort1Pin9ToPintsel);

    const uint32_t port0_pin29_config = (/* Pin is configured as FC0_RXD_SDA_MOSI_DATA */
                                         IOCON_PIO_FUNC1 |
                                         /* No addition pin function */
                                         IOCON_PIO_MODE_INACT |
                                         /* Standard mode, output slew rate control is enabled */
                                         IOCON_PIO_SLEW_STANDARD |
                                         /* Input function is not inverted */
                                         IOCON_PIO_INV_DI |
                                         /* Enables digital function */
                                         IOCON_PIO_DIGITAL_EN |
                                         /* Open drain is disabled */
                                         IOCON_PIO_OPENDRAIN_DI);
    /* PORT0 PIN29 (coords: 92) is configured as FC0_RXD_SDA_MOSI_DATA */
    IOCON_PinMuxSet(IOCON, 0U, 29U, port0_pin29_config);

    const uint32_t port0_pin30_config = (/* Pin is configured as FC0_TXD_SCL_MISO_WS */
                                         IOCON_PIO_FUNC1 |
                                         /* No addition pin function */
                                         IOCON_PIO_MODE_INACT |
                                         /* Standard mode, output slew rate control is enabled */
                                         IOCON_PIO_SLEW_STANDARD |
                                         /* Input function is not inverted */
                                         IOCON_PIO_INV_DI |
                                         /* Enables digital function */
                                         IOCON_PIO_DIGITAL_EN |
                                         /* Open drain is disabled */
                                         IOCON_PIO_OPENDRAIN_DI);
    /* PORT0 PIN30 (coords: 94) is configured as FC0_TXD_SCL_MISO_WS */
    IOCON_PinMuxSet(IOCON, 0U, 30U, port0_pin30_config);

    const uint32_t port1_pin10_config = (/* Pin is configured as PIO1_4 */
                                            IOCON_PIO_FUNC0 |
                                            /* Selects pull-up function */
    										IOCON_PIO_MODE_INACT |
                                            /* Standard mode, output slew rate control is enabled */
                                            IOCON_PIO_SLEW_STANDARD |
                                            /* Input function is not inverted */
                                            IOCON_PIO_INV_DI |
                                            /* Enables digital function */
                                            IOCON_PIO_DIGITAL_EN |
                                            /* Open drain is disabled */
                                            IOCON_PIO_OPENDRAIN_DI);
        /* PORT1 PIN4 (coords: 1) is configured as PIO1_4 */
        IOCON_PinMuxSet(IOCON, 1U, 10U, port1_pin10_config);

        const uint32_t port1_pin9_config = (/* Pin is configured as PIO1_4 */
                                            IOCON_PIO_FUNC0 |
                                            /* Selects pull-up function */
    										IOCON_PIO_MODE_INACT |
                                            /* Standard mode, output slew rate control is enabled */
                                            IOCON_PIO_SLEW_STANDARD |
                                            /* Input function is not inverted */
                                            IOCON_PIO_INV_DI |
                                            /* Enables digital function */
                                            IOCON_PIO_DIGITAL_EN |
                                            /* Open drain is disabled */
                                            IOCON_PIO_OPENDRAIN_DI);
        /* PORT1 PIN4 (coords: 1) is configured as PIO1_4 */
        IOCON_PinMuxSet(IOCON, 1U, 9U, port1_pin9_config);

        const uint32_t port0_pin15_config = (/* Pin is configured as PIO1_4 */
                                            IOCON_PIO_FUNC0 |
                                            /* Selects pull-up function */
                                            IOCON_PIO_MODE_PULLUP |
                                            /* Standard mode, output slew rate control is enabled */
                                            IOCON_PIO_SLEW_STANDARD |
                                            /* Input function is not inverted */
                                            IOCON_PIO_INV_DI |
                                            /* Enables digital function */
                                            IOCON_PIO_DIGITAL_EN |
                                            /* Open drain is disabled */
                                            IOCON_PIO_OPENDRAIN_DI);
        /* PORT1 PIN4 (coords: 1) is configured as PIO1_4 */
        IOCON_PinMuxSet(IOCON, 0U, 15U, port0_pin15_config);

        const uint32_t port1_pin4_config = (/* Pin is configured as PIO1_4 */
                                            IOCON_PIO_FUNC0 |
                                            /* Selects pull-up function */
                                            IOCON_PIO_MODE_PULLUP |
                                            /* Standard mode, output slew rate control is enabled */
                                            IOCON_PIO_SLEW_STANDARD |
                                            /* Input function is not inverted */
                                            IOCON_PIO_INV_DI |
                                            /* Enables digital function */
                                            IOCON_PIO_DIGITAL_EN |
                                            /* Open drain is disabled */
                                            IOCON_PIO_OPENDRAIN_DI);
        /* PORT1 PIN4 (coords: 1) is configured as PIO1_4 */
        IOCON_PinMuxSet(IOCON, 1U, 4U, port1_pin4_config);

        const uint32_t port0_pin19_config = (/* Pin is configured as FC7_TXD_SCL_MISO_WS */
                                             IOCON_PIO_FUNC7 |
                                             /* Selects pull-up function */
                                             IOCON_PIO_MODE_PULLUP |
                                             /* Standard mode, output slew rate control is enabled */
                                             IOCON_PIO_SLEW_STANDARD |
                                             /* Input function is not inverted */
                                             IOCON_PIO_INV_DI |
                                             /* Enables digital function */
                                             IOCON_PIO_DIGITAL_EN |
                                             /* Open drain is disabled */
                                             IOCON_PIO_OPENDRAIN_DI);
        /* PORT0 PIN19 (coords: 90) is configured as FC7_TXD_SCL_MISO_WS */
        IOCON_PinMuxSet(IOCON, 0U, 19U, port0_pin19_config);

        const uint32_t port0_pin20_config = (/* Pin is configured as FC7_RXD_SDA_MOSI_DATA */
                                             IOCON_PIO_FUNC7 |
                                             /* Selects pull-up function */
                                             IOCON_PIO_MODE_PULLUP |
                                             /* Standard mode, output slew rate control is enabled */
                                             IOCON_PIO_SLEW_STANDARD |
                                             /* Input function is not inverted */
                                             IOCON_PIO_INV_DI |
                                             /* Enables digital function */
                                             IOCON_PIO_DIGITAL_EN |
                                             /* Open drain is disabled */
                                             IOCON_PIO_OPENDRAIN_DI);
        /* PORT0 PIN20 (coords: 74) is configured as FC7_RXD_SDA_MOSI_DATA */
        IOCON_PinMuxSet(IOCON, 0U, 20U, port0_pin20_config);

        const uint32_t port0_pin21_config = (/* Pin is configured as FC7_SCK */
                                             IOCON_PIO_FUNC7 |
                                             /* Selects pull-up function */
                                             IOCON_PIO_MODE_PULLUP |
                                             /* Standard mode, output slew rate control is enabled */
                                             IOCON_PIO_SLEW_STANDARD |
                                             /* Input function is not inverted */
                                             IOCON_PIO_INV_DI |
                                             /* Enables digital function */
                                             IOCON_PIO_DIGITAL_EN |
                                             /* Open drain is disabled */
                                             IOCON_PIO_OPENDRAIN_DI);
        /* PORT0 PIN21 (coords: 76) is configured as FC7_SCK */
        IOCON_PinMuxSet(IOCON, 0U, 21U, port0_pin21_config);

        const uint32_t port1_pin20_config = (/* Pin is configured as FC7_RTS_SCL_SSEL1 */
                                             IOCON_PIO_FUNC1 |
                                             /* Selects pull-up function */
                                             IOCON_PIO_MODE_PULLUP |
                                             /* Standard mode, output slew rate control is enabled */
                                             IOCON_PIO_SLEW_STANDARD |
                                             /* Input function is not inverted */
                                             IOCON_PIO_INV_DI |
                                             /* Enables digital function */
                                             IOCON_PIO_DIGITAL_EN |
                                             /* Open drain is disabled */
                                             IOCON_PIO_OPENDRAIN_DI);
        /* PORT1 PIN20 (coords: 4) is configured as FC7_RTS_SCL_SSEL1 */
        IOCON_PinMuxSet(IOCON, 1U, 20U, port1_pin20_config);


        //FLEXCOM8

        const uint32_t port0_pin26_config = (/* Pin is configured as HS_SPI_MOSI */
                                                 IOCON_PIO_FUNC9 |
                                                 /* No addition pin function */
                                                 IOCON_PIO_MODE_INACT |
                                                 /* Fast mode, slew rate control is disabled */
                                                 IOCON_PIO_SLEW_FAST |
                                                 /* Input function is not inverted */
                                                 IOCON_PIO_INV_DI |
                                                 /* Enables digital function */
                                                 IOCON_PIO_DIGITAL_EN |
                                                 /* Open drain is disabled */
                                                 IOCON_PIO_OPENDRAIN_DI);
            /* PORT0 PIN26 (coords: 60) is configured as HS_SPI_MOSI */
            IOCON_PinMuxSet(IOCON, 0U, 26U, port0_pin26_config);

            const uint32_t port1_pin1_config = (/* Pin is configured as HS_SPI_SSEL1 */
                                                IOCON_PIO_FUNC5 |
                                                /* No addition pin function */
                                                IOCON_PIO_MODE_INACT |
                                                /* Fast mode, slew rate control is disabled */
                                                IOCON_PIO_SLEW_FAST |
                                                /* Input function is not inverted */
                                                IOCON_PIO_INV_DI |
                                                /* Enables digital function */
                                                IOCON_PIO_DIGITAL_EN |
                                                /* Open drain is disabled */
                                                IOCON_PIO_OPENDRAIN_DI);
            /* PORT1 PIN1 (coords: 59) is configured as HS_SPI_SSEL1 */
            IOCON_PinMuxSet(IOCON, 1U, 1U, port1_pin1_config);

            const uint32_t port1_pin2_config = (/* Pin is configured as HS_SPI_SCK */
                                                IOCON_PIO_FUNC6 |
                                                /* No addition pin function */
                                                IOCON_PIO_MODE_INACT |
                                                /* Fast mode, slew rate control is disabled */
                                                IOCON_PIO_SLEW_FAST |
                                                /* Input function is not inverted */
                                                IOCON_PIO_INV_DI |
                                                /* Enables digital function */
                                                IOCON_PIO_DIGITAL_EN |
                                                /* Open drain is disabled */
                                                IOCON_PIO_OPENDRAIN_DI);
            /* PORT1 PIN2 (coords: 61) is configured as HS_SPI_SCK */
            IOCON_PinMuxSet(IOCON, 1U, 2U, port1_pin2_config);

            const uint32_t port1_pin3_config = (/* Pin is configured as HS_SPI_MISO */
                                                IOCON_PIO_FUNC6 |
                                                /* No addition pin function */
                                                IOCON_PIO_MODE_INACT |
                                                /* Fast mode, slew rate control is disabled */
                                                IOCON_PIO_SLEW_FAST |
                                                /* Input function is not inverted */
                                                IOCON_PIO_INV_DI |
                                                /* Enables digital function */
                                                IOCON_PIO_DIGITAL_EN |
                                                /* Open drain is disabled */
                                                IOCON_PIO_OPENDRAIN_DI);
            /* PORT1 PIN3 (coords: 62) is configured as HS_SPI_MISO */
            IOCON_PinMuxSet(IOCON, 1U, 3U, port1_pin3_config);


    IOCON->PIO[0][5] = ((IOCON->PIO[0][5] &
                         /* Mask bits to zero which are setting */
                         (~(IOCON_PIO_FUNC_MASK)))

                        /* Selects pin function.
                         * : PORT05 (pin 88) is configured as SECURE_GPIO0_5. */
                        | IOCON_PIO_FUNC(0x0Au));

    IOCON->PIO[1][18] = ((IOCON->PIO[1][18] &
                          /* Mask bits to zero which are setting */
                          (~(IOCON_PIO_FUNC_MASK | IOCON_PIO_MODE_MASK | IOCON_PIO_DIGIMODE_MASK)))

                         /* Selects pin function.
                          * : PORT118 (pin 64) is configured as PIO1_18. */
                         | IOCON_PIO_FUNC(PIO1_18_FUNC_ALT0)

                         /* Selects function mode (on-chip pull-up/pull-down resistor control).
                          * : Pull-up.
                          * Pull-up resistor enabled. */
                         | IOCON_PIO_MODE(PIO1_18_MODE_PULL_UP)

                         /* Select Digital mode.
                          * : Digital mode, digital input is enabled. */
                         | IOCON_PIO_DIGIMODE(PIO1_18_DIGIMODE_DIGITAL));

//    IOCON->PIO[1][9] = ((IOCON->PIO[1][9] &
//    		/* Mask bits to zero which are setting */
//    		(~(IOCON_PIO_FUNC_MASK | IOCON_PIO_MODE_MASK | IOCON_PIO_DIGIMODE_MASK)))
//
//    		/* Selects pin function.
//    		 * : PORT19 (pin 10) is configured as PIO1_9. */
//    		| IOCON_PIO_FUNC(PIO1_9_FUNC_ALT0)
//
//			/* Selects function mode (on-chip pull-up/pull-down resistor control).
//			 * : Pull-up.
//			 * Pull-up resistor enabled. */
//			| IOCON_PIO_MODE(PIO1_9_MODE_PULL_UP)
//
//			/* Select Digital mode.
//			 * : Digital mode, digital input is enabled. */
//			| IOCON_PIO_DIGIMODE(PIO1_9_DIGIMODE_DIGITAL));
}
/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
